name: Cypress CI
on: [push, pull_request] # Se lance à chaque push ou PR

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

  - name: Récupérer le code
    uses: actions/checkout@v4

  - name: Lancer les tests Cypress
    uses: cypress-io/github-action@v6
    with:
      # Étape pour installer les dépendances et builder si besoin
      build: npm run build
      # Commande pour démarrer ton serveur
      start: npm start
