name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Start PHP server
        run: php -S localhost:9000 &

      - name: Cypress run
        uses: cypress-io/github-action@v7